name: qr_mobile_vision_example
description: Demonstrates how to use the qr_mobile_vision plugin.

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  qr_mobile_vision:
    path: ../

flutter:
  uses-material-design: true